image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/

tasks:
  - name: term 01
    #init: curl -fsSL https://install.julialang.org | sh # runs during prebuild
    command: julia pkgs_activator.jl

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview


